version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_pass
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  db:
    image: mysql:8.0
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - $PWD/storage/v_mysql:/var/lib/mysql
      
      

volumes:
  rabbitmq1:
  v_mysql: